version=1.0


[[datasets]]

  key="Hanlon_2022"

  [datasets.publication]
  doi="10.12688/wellcomeopenres.17208.2"
  eligibility_criteria="Criteria for inclusion, defined according to PECOS (Population, Exposure, Comparator, Outcome, Setting and Study design)14, including outcomes of interest are detailed in Table 1. Criteria were deliberately broad in terms of setting, frailty definition, and outcomes. Briefly, studies must include adults (≥18 years) with rheumatoid arthritis and assess frailty, although we expect studies may mainly involve ‘older’ populations. Studies were considered regardless of frailty measure, to allow comparison between different methods of identifying frailty. These could include validated measures of frailty (e.g. frailty phenotype or frailty index), adaptations of these measures where the adaptation was described, or unvalidated measures intended to capture frailty as long as the criteria used to define frailty within the study were fully described. We did not exclude studies on the basis of the criteria used to define rheumatoid arthritis (i.e. validated criteria, physician diagnosis, medical record/clinical codes or self-reported definitions were all eligible for inclusion). We included studies in any setting (community, outpatient, or inpatient). Observational studies with cross-sectional or cohort designs were eligible for inclusion. Experimental studies were excluded. When examining the association between frailty and clinical outcomes in those with rheumatoid arthritis, studies were expected to report the association between frailty and the outcome of interest. As in previous reviews of frailty15,16, considered studies that describe this either as the association with the presence or absence of frailty or the association between the degree of frailty and the outcome."
  
  [datasets.data]
  doi="10.5281/zenodo.6966157"


[[datasets]]

  key="Abgaz_2023"

  [datasets.publication]
  doi="10.1109/tse.2023.3287297"
  eligibility_criteria="Studies were screened by applying the following exclusion criteria (EC): (EC1) Duplicate Study, (EC2) Books and Patents, (EC3) Non-peer-reviewed Study, (EC4) Secondary Study, (EC5) Study written in languages other than English, and (EC6) Study published before 2015. Note that there is an additional step at the end of the process to protect against oversight of significant pre-2015 published material (details of which are provided at the end of this subsection). Further studies that did not satisfy the inclusion criteria were removed. The three inclusion criteria (IC) are: (IC1) the primary objective of the study should be the decomposition of monolith applications into microservices, (IC2) the study should include structured and preferably automatic or semi-automatic decomposition approaches, and (IC3) the study should sufficiently describe the decomposition method, code, algorithm, and its evaluation (i.e., abstracts and extended abstracts are not included)."
  
  [datasets.data]
  doi="10.5281/zenodo.7899996"


[[datasets]]

  key="van_Ballegooijen_2024"

  [datasets.publication]
  doi="10.1001/jamapsychiatry.2024.2854"
  eligibility_criteria = "Studies were included if they met the following criteria: (1) had a randomized design comparing 2 or more groups; (2) examined psychotherapy (the use of psychological methods to change behavior or overcome problems) targeting any mental health problem and delivered in any setting (including guided digital treatments); (3) compared the intervention with a control group (such as care as usual, enhanced care as usual, or waiting list); (4) reported suicidal ideation (SI), suicide attempts (SA), or self-harm leading to hospitalization (only included if the authors’ definition of self-harm included suicide attempts). Studies were excluded if they (1) used an intervention that did not involve any psychotherapeutic technique or support (eg, unguided self-help and community intervention) and (2) measured SI on a categorical scale, such as a single item of a questionnaire for depression. We included studies on all age groups."

  [datasets.data]
  url="https://surfdrive.surf.nl/files/index.php/s/UcfIYP3K612w0oA"


[[datasets]]

  key="Sanchez-Gomez_2024"

  [datasets.publication]
  doi="10.3390/bs14040308"
  eligibility_criteria = "The first filter (abstract level) verified the following criteria: (i) empirical studies; (ii) narrative skills assessed in children or adolescents; (iii) were not case studies; (iv) published between 2010 and 2023; and (v) manuscript written in English or Spanish. Empirical studies included descriptive studies, experiments, quasi-experimental studies, ex post facto designs, and instrumental studies. In a second filter (full text), the selection was limited to those studies in which (i) statistics on the measurements are included and (ii) oral narratives are assessed (e.g., written narratives were excluded). Finally, regarding the target population, all the studies that considered participants who were children or adolescents with ID were include, even if they also included adults, TD participants, or participants with other diagnosis (e.g., studies with participant with autism but without ID were excluded, participants with autism and ID were included). The final criterion applied was the inclusion of participants with ID (third filter)."

  [datasets.data]
  url="https://osf.io/tg56j/"


[[datasets]]

  key="Maciel_2024"

  [datasets.publication]
  doi="10.1080/07481187.2024.2419605"
  eligibility_criteria = "Studies were included if they (a) reported primary empirical data, (b) were written in English, Portuguese, Spanish or French, (c) had adult participants (mean age > 18 years), (d) reported quantitative assessments of suicidal ideation or suicide attempt, investigated either by dichotomous questions or validated scales, (e) used validated instruments to assess adult attachment styles, either self-report or interview measures, categorical or dimensional. There were no restrictions on study design, setting, or sample characteristics other than age."

  [datasets.data]
  url="https://osf.io/e4pn9/"


[[datasets]]
  # The doi is invalid, but the paper is indexed in OpenAlex

  key="Giesen_2021"

  [datasets.publication]
  doi="10.29011/26889501.101265"
  url="https://www.gavinpublishers.com/article/view/overview-of-pain-interventions-for-hospital-and-community-care-nurses-a-systematic-scoping-review"
  eligibility_criteria = "Original research articles written in English or Dutch, published in peer journals in or after 2010 were eligible. We chose only to select studies published after 2010 to ensure inclusion of recent and up-to-date scientific nursing outcomes. According to the guidance of the Cochrane Effective Practice and Organization of Care group, studies were included if the data could be compared with a control or baseline measure, such as randomised controlled trials, controlled before-and-after studies or interrupted time series methods. In addition, the studies had to include interventions of a Western origin, be focused on pain care performed by a nurse and include adult patients >18 years. Finally, studies had to be conducted in a hospital or community care setting or contain an intervention transferable to these settings and executed in an Organisation for Economic Co-operation and Development country. Studies involving women in labour or breastfeeding and/or Chinese, alternative or non-Western interventions were excluded."

  [datasets.data]
  url="https://osf.io/gnyt4/"


[[datasets]]

  key="Bakker-Jacobs_2022"

  [datasets.publication]
  doi="10.29011/2688-9501.101268"
  eligibility_criteria = "Original research written in English or Dutch and published in peer journals in or after 2010 was considered eligible. We chose only to select studies published after 2010 to ensure inclusion of recent and up-to-date scientific nursing outcomes. According to the guidance of the Cochrane Effective Practice and Organization of Care group, studies were included if data could be compared with a control or baseline measure, such as randomised controlled trials, controlled before-and-after studies or interrupted time series methods. In addition, the interventions in the studies had to be of Western origin and had to be focused on wound care performed by a nurse on adult patients (>18 years). Finally, the studies had to be conducted in a hospital or community care setting of an Organisation for Economic Co-operation and Development country. Studies involving interventions aimed at wounds due to labour or breastfeeding as well as papers involving burns or special pressure-relieving mattresses were excluded. Studies concerning Chinese, alternative or non-Western medicine were also excluded."

  [datasets.data]
  url="https://osf.io/qhk3v/"


[[datasets]]

  key="Wijnen_2024"

  [datasets.publication]
  doi="10.5194/gc-7-91-2024"

  [datasets.data]
  doi="10.5281/zenodo.13957522"


[[datasets]]

  key="Boersma-van_Dam_2024"

  [datasets.publication]
  doi="https://doi.org/10.1080/17437199.2024.2423725"
  eligibility_criteria = "Studies were included if they met the following criteria: (1) Original full-text publications in English in a peer-reviewed journal; (2) Participants were adult burn survivors with any level of burn severity treated at a health care facility (both inpatient and outpatient samples were eligible); (3) in the case of mixed-trauma populations, separate statistics for burn survivors needed to be available; (4) a non-selective sampling method was used (e.g., including all consecutive burn survivors at a certain burn facility or after a disaster); (5) PTSD (or PTSD symptomatology) was assessed by a (semi) structured interview based on recognised diagnostic criteria for PTSD or a validated self-report PTSD questionnaire; and (6) sufficient information was provided to calculate prevalence rates and their standard error (i.e., the sample size and the number or percentage of PTSD cases). Studies of paediatric burns populations were excluded to focus on a homogeneous sample. Studies that reported the combined prevalence of a wider population (e.g., ‘injuries’) and studies with likely epidemiologically selective samples, such as qualitative studies, case reports, randomised controlled trials, effect studies, reviews, studies with sample sizes of fewer than ten participants, or studies including only combat casualties or complex multi-trauma survivors were also excluded. After the quality appraisal and data extraction, one post-hoc exclusion criterium was applied for the meta-analysis: studies that did not measure PTSD prevalence within 3 months around a specified time point following the event leading to the burn or discharge from hospital, and study estimates after 24 months post-burn, were excluded from the meta-analysis (see statistical analyses)."

  [datasets.data]
  doi="https://osf.io/wjnbz/"


[[datasets]]

  key="Hall_2012"

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

  [datasets.publication]
  doi="10.1109/TSE.2011.103"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

  key="Cozim-Melges_2024"

  [datasets.publication]
  doi="10.1038/s44185-023-00034-2"
  eligibility_criteria = "Criteria of inclusion: (I1) English text and; (I2) published and peer-reviewed and; (I3) with discriminated agricultural practices and; (I4) with specific targeted species and; (I5) on a scale ranging from farm to landscape and; (I6) focused on the biodiversity of agroecosystems and; (I7) sampled data from real life scenarios. Criteria of exclusion: (E1) no methods to calculate statistical significance or; (E2) laboratory studies or Greenhouse Studies or; (E3) no explicit methodology and a varying control object (e.g. crops) or targeted species of the study or; (E4) no control group established or relatable to our reference or; (E5) no discrimination between practices impacts on surrogate species."

  [datasets.data]
  # data is in supplemental material of paper
  doi="10.1038/s44185-023-00034-2"


[[datasets]]

  key="Radjenovic_2013"

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

  [datasets.publication]
  doi="10.1016/j.infsof.2013.02.009"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]
  doi="10.1007/s40262-021-01042-w"

  [datasets.data]
  url="https://osf.io/tnxju/"


[[datasets]]

  key="Meijboom_2021"

  [datasets.publication]
  doi="10.1007/s40259-021-00508-4"

  [datasets.data]
  url="https://osf.io/4cdku/"

[[datasets]]

  key="van_der_Valk_2021"

  [datasets.publication]
  doi="10.1111/obr.13376"

  [datasets.data]
  doi="10.17605/OSF.IO/WDZH5"


[[datasets]]

  key="Smid_2020"

  [datasets.publication]
  doi="10.1080/10705511.2019.1577140"

  [datasets.data]
  doi="10.17605/OSF.IO/PUQ7X"


[[datasets]]

  key="Brouwer_2019"

  [datasets.publication]
  doi="10.1016/j.cpr.2019.101773"

  [datasets.data]
  doi="10.17605/OSF.IO/R45YZ"


[[datasets]]

  key="Appenzeller-Herzog_2019"

  [datasets.publication]
  doi="10.1111/liv.14179"

  [datasets.data]
  doi="10.5281/zenodo.3625931"


[[datasets]]

  key="Bos_2018"

  [datasets.publication]
  doi="10.1016/j.jalz.2018.04.007"

  [datasets.data]
  url="https://osf.io/w3kbq/"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Nelson_2002"

  [datasets.publication]
  doi="10.1001/jama.288.7.872"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]
  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2004"

  [datasets.publication]
  doi="10.1016/j.jpainsymman.2004.05.002"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]
  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2003"

  [datasets.publication]
  doi="10.1016/j.jpainsymman.2003.03.003"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]
  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"


[[datasets]]

  # Note, this dataset is also used for another systematic review:
  # https://doi.org/10.1080/10705511.2016.1247646

  key="van_de_Schoot_2018"

  [datasets.publication]
  doi="10.1080/00273171.2017.1412293"

  [datasets.data]
  doi="10.17605/OSF.IO/VW3T7"


[[datasets]]

  key="van_Dis_2020"

  [datasets.publication]
  doi="10.1001/jamapsychiatry.2019.3986"

  [datasets.data]
  url="https://osf.io/4d9tu/"


[[datasets]]

  key="Wolters_2018"

  [datasets.publication]
  doi="10.1016/j.jalz.2018.01.007"

  [datasets.data]
  url="https://osf.io/sxzjg/"


[[datasets]]

  key="Leenaars_2019"

  [datasets.publication]
  doi="10.5334/jcr.183"

  [datasets.data]
  doi="10.17605/OSF.IO/PH56S"


[[datasets]]

  key="Menon_2022"

  [datasets.publication]
  doi="10.1080/10408444.2022.2082917"

  [datasets.data]
  url="https://osf.io/9jzsu"


[[datasets]]

  key="van_der_Waal_2022"

  [datasets.publication]
  doi="10.1016/j.jgo.2022.09.012"

  [datasets.data]
  doi="10.5281/zenodo.7308296"


[[datasets]]

  key="Muthu_2021"

  [datasets.publication]
  doi="10.1097/BRS.0000000000003645"

  [datasets.data]
  url="https://osf.io/68ezp"


[[datasets]]

  key="Jeyaraman_2020"

  [datasets.publication]
  doi="10.1177/1947603520951623"

  [datasets.data]
  url="https://osf.io/8drsc/"


[[datasets]]

  key="Moran_2021"

  [datasets.publication]
  doi="10.1111/brv.12655"

  [datasets.data]
  doi="10.17605/OSF.IO/3TPHJ"


[[datasets]]

  key="Oud_2018"

  [datasets.publication]
  doi="10.1177/0004867418791257"

  [datasets.data]
  url="https://osf.io/pjr97"


[[datasets]]

  key="Wassenaar_2017"

  [datasets.publication]
  doi="10.1289/ehp1233"

  [datasets.data]
  doi="10.1186/s13643-016-0263-z"


[[datasets]]

  key="Walker_2018"

  [datasets.collection]
  doi="10.1186/s13643-016-0263-z"

  [datasets.publication]
  doi="10.1016/j.envint.2017.12.032"

  [datasets.data]
  doi="10.1186/s13643-016-0263-z"


[[datasets]]

  key="Leenaars_2020"

  [datasets.publication]
  doi="10.3390/ani10061047"

  [datasets.data]
  doi="10.17605/OSF.IO/T7GYR"


[[datasets]]

  key="Sep_2021"

  [datasets.publication]
  doi="10.1371/journal.pone.0249102"

  [datasets.data]
  doi="10.17605/OSF.IO/GY2MC"

[[datasets]]

  key="Brons_2024"

  [datasets.publication]
  doi="10.2196/47774"
  eligibility_criteria="Studies were included if they met the following criteria: (1) Articles: peer-reviewed articles, conference proceedings, or book chapters on qualitative, quantitative, and mixed method studies or protocols; (2) Language: English; (3) Application: digital intervention, either stand-alone or hybrid with a health care provider, with at least one personalized persuasive strategy; (4) Machine learning (ML) technique: supervised ML, unsupervised ML, or reinforcement learning; (5) Health behavior promoted by the intervention: physical activity (including walking, running, cycling, performing exercises, and performing sports activities) either alone or as part of several health behaviors. Studies were excluded if they (1) Articles: conference abstracts, reviews, letters, editorials, comments, non–peer-reviewed articles or book chapters, white papers, or articles with no full text available; (2) Language: all other languages; (3) Application: nonadaptive intervention or persuasive strategy not specified; (4) ML technique: rule-based if-then systems, predefined formulas, manual personalization, ML method not specified, computer vision, natural language processing, or robotics; (5) Health behavior promoted by the intervention: health behaviors other than physical activity."

  [datasets.data]
  doi="10.17605/OSF.IO/VJQ59"

[[datasets]]

  key="Pinos-Cisneros_2023"

  [datasets.publication]
  doi="10.2196/44904"
  eligibility_criteria="The inclusion criteria for the analyzed articles were as follows: (1) study participants were children (aged 0-18 years) with spastic CP; (2) the therapy described was focused on hands or upper limbs motor skills; (3) the therapy used innovative technology (ie, electronic tools, systems, and devices); (4) the therapy used playful elements such as video games or toys; and (5) the publications consisted of peer-reviewed academic articles or conference proceedings that were published between 2009 and 2022. The exclusion criteria included (1) insufficient information about the game or play activity or referred to traditional therapies without the support of technologies (eg, bimanual, constrained-induced movement, and Pirate Therapy), (2) lack of focus on the treatment used, (3) written in a different language than English, (4) unavailability to access the full text at the time of analysis, and (5) incomplete inclusion criteria. Disagreements between reviewers with regard to the exclusion criteria were resolved through discussion."
  
  [datasets.data]
  doi="10.17605/OSF.IO/MK76S"
